apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-app
  labels:
    app: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "httpbin-app"
        dapr.io/app-port: "80"
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        name: httpbin
        ports:
        - containerPort: 80